name: Triggered PowerShell Action

on:
  workflow_dispatch:
    inputs:
      Identity:
        description: 'Identity Variables passed from power automate'
        required: true
      Type:
        description: 'Type Variable passed from power automate'
        required: true
      AccessToken:
        description: 'AccessToken Variables passed from power automate'
        required: true

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute PowerShell Script
        run: .\script.ps1 -Identity ${{ github.event.inputs.Identity }} -Type ${{ github.event.inputs.Type }} -AccessToken ${{ github.event.inputs.AccessToken }}
